baseURL = "https://catalogue.projectsbyif.com/"
languageCode = "en-uk"
title = "Design Patterns Catalogue"
[params]
  twitterText = " from the patterns catalogue curated by @projectsbyif #patternsbyif"
  twitterHandle = "projectsbyif"
enableGitInfo = true
