baseURL = "http://example.org/"
languageCode = "en-uk"
title = "Data Patterns"
[params]
  twitterText = "This pattern from the Data Patterns catalogue can help design services that involve data sharing."
  twitterHandle = "projectsbyif"
