baseURL = "http://example.org/"
languageCode = "en-uk"
title = "Patterns Catalogue"
[params]
  twitterText = " from the Data Patterns Catalogue curated by @projectsbyif #patternsbyif"
  twitterHandle = "projectsbyif"
enableGitInfo = true
